import { StaticImageData } from 'next/image'
import animais from '@/assets/animais.png'
import frutas from '@/assets/frutas.png'
import objetos from '@/assets/objetos.png'
import cores from '@/assets/cores.png'
import paises from '@/assets/paises.png'
import profissoes from '@/assets/profissoes.png'
import esportes from '@/assets/esportes.png'

const categories: {
  [key: string]: {
    words: string[]
    image: StaticImageData
    hints: { [key: string]: string[] }
  }
} = {
  animais: {
    words: [
      'cachorro',
      'gato',
      'elefante',
      'tigre',
      'leao',
      'girafa',
      'urso',
      'coelho',
      'raposa',
      'veado',
      'pato',
      'galinha',
      'vaca',
      'cavalo',
      'borboleta',
      'abelha',
      'formiga',
      'aranha',
      'escorpiao',
      'lagarto',
      'cobra',
      'jacare',
      'tartaruga',
      'peixe',
    ],
    image: animais,
    hints: {
      pato: ['ave', 'nada', 'quack', 'Donald', 'Daisy'],
      galinha: ['ave', 'casa', 'ovo', 'pintinho', 'caipira'],
      vaca: ['mamifero', 'leite', 'mugir', 'fazenda', 'manchas'],
      cavalo: ['mamifero', 'corre', 'montaria', 'selaria', 'potro'],
      borboleta: ['inseto', 'asas', 'colorida', 'casulo', 'voa'],
      abelha: ['inseto', 'mel', 'zumbido', 'colmeia', 'rainha'],
      formiga: ['inseto', 'trabalhadora', 'formigueiro', 'carrega', 'rainha'],
      aranha: ['inseto', 'teia', 'pernas', 'peconhenta', 'preta'],
      escorpiao: ['inseto', 'veneno', 'pinca', 'cauda', 'noturno'],
      lagarto: ['reptil', 'escamas', 'cauda', 'corre', 'verde'],
      cobra: ['reptil', 'veneno', 'rasteja', 'sibila', 'fria'],
      jacare: ['reptil', 'agua', 'dentes', 'cauda', 'verde'],
      tartaruga: ['reptil', 'casco', 'lenta', 'marinha', 'terra'],
      peixe: ['agua', 'nadadeiras', 'escamas', 'respira', 'frio'],
    },
  },
  frutas: {
    words: [
      'maca',
      'banana',
      'laranja',
      'uva',
      'melancia',
      'abacaxi',
      'morango',
      'manga',
      'kiwi',
      'pera',
      'pessego',
      'ameixa',
      'limao',
      'abacate',
      'caqui',
      'pitaya',
      'pitanga',
    ],
    image: frutas,
    hints: {
      maca: ['vermelha', 'fruta', 'mae', 'dourada', 'verde'],
      banana: ['amarela', 'fruta', 'casca', 'prata', 'nanica'],
      laranja: ['citrica', 'fruta', 'suco', 'casca', 'vitamina'],
      uva: ['roxa', 'fruta', 'cacho', 'vinho', 'doce'],
      melancia: ['verde', 'fruta', 'doce', 'vermelha', 'semente'],
      abacaxi: ['amarelo', 'fruta', 'doce', 'casca', 'coroa'],
      morango: ['vermelho', 'fruta', 'doce', 'acido', 'chocolate'],
      manga: ['amarela', 'fruta', 'doce', 'suco', 'casca'],
      kiwi: ['verde', 'fruta', 'doce', 'acido', 'casca'],
      pera: ['verde', 'fruta', 'doce', 'suco', 'casca'],
      pessego: ['laranja', 'fruta', 'doce', 'peludo', 'caroco'],
      ameixa: ['roxa', 'fruta', 'doce', 'casca', 'caroco'],
      limao: ['verde', 'fruta', 'acido', 'suco', 'casca'],
      abacate: ['verde', 'fruta', 'doce', 'salgado', 'casca'],
      caqui: ['laranja', 'fruta', 'doce', 'casca', 'semente'],
      pitaya: ['rosa', 'fruta', 'doce', 'casca', 'espinhos'],
      pitanga: ['vermelha', 'fruta', 'doce', 'casca', 'caroco'],
    },
  },
  objetos: {
    words: [
      'mesa',
      'cadeira',
      'computador',
      'telefone',
      'livro',
      'caderno',
      'caneta',
      'lapis',
      'janela',
      'porta',
      'cama',
      'travesseiro',
      'cobertor',
      'abajur',
      'sofa',
      'televisao',
      'geladeira',
      'fogao',
      'microondas',
      'liquidificador',
    ],
    image: objetos,
    hints: {
      mesa: ['madeira', 'quatro', 'pata', 'comer', 'sentar'],
      cadeira: ['sentar', 'encosto', 'quatro', 'pata', 'madeira'],
      computador: ['teclado', 'mouse', 'monitor', 'internet', 'trabalho'],
      telefone: ['ligar', 'celular', 'falar', 'ouvir', 'discar'],
      livro: ['ler', 'folhas', 'pagina', 'capa', 'autor'],
      caderno: ['escrever', 'folhas', 'escola', 'materia', 'capa'],
      caneta: ['escrever', 'tinta', 'ponta', 'cor', 'marca'],
      lapis: ['escrever', 'grafite', 'apontar', 'borracha', 'madeira'],
      janela: ['vidro', 'abrir', 'fechar', 'ver', 'ventilar'],
      porta: ['abrir', 'fechar', 'entrar', 'sair', 'casa'],
      cama: ['dormir', 'colchao', 'lençol', 'travesseiro', 'quarto'],
      travesseiro: ['dormir', 'cama', 'macio', 'quarto', 'cabeça'],
      cobertor: ['dormir', 'cama', 'quente', 'frio', 'inverno'],
      abajur: ['luz', 'escuro', 'quarto', 'mesa', 'lampada'],
      sofa: ['sentar', 'descansar', 'quarto', 'sala', 'confortavel'],
      televisao: ['ver', 'imagem', 'som', 'canal', 'controle'],
      geladeira: ['comida', 'frio', 'cozinha', 'porta', 'congelar'],
      fogao: ['cozinhar', 'forno', 'panela', 'fogo', 'gas'],
      microondas: ['cozinhar', 'aquecer', 'comida', 'forno', 'rapido'],
      liquidificador: ['misturar', 'liquidificar', 'comida', 'copo', 'motor'],
    },
  },
  cores: {
    words: [
      'vermelho',
      'azul',
      'amarelo',
      'verde',
      'preto',
      'branco',
      'cinza',
      'rosa',
      'roxo',
      'marrom',
      'laranja',
      'violeta',
      'bege',
      'dourado',
      'prateado',
      'turquesa',
      'ciano',
      'magenta',
      'salmao',
      'creme',
      'chocolate',
      'caramelo',
      'grafite',
    ],
    image: cores,
    hints: {
      vermelho: ['sangue', 'coracao', 'fogo', 'paixao', 'rosa'],
      azul: ['ceu', 'mar', 'frio', 'calmo', 'branco'],
      amarelo: ['sol', 'ouro', 'alegria', 'banana', 'vermelho'],
      verde: ['mato', 'folha', 'esperanca', 'limao', 'azul'],
      preto: ['escuro', 'noite', 'luto', 'branco', 'vermelho'],
      branco: ['neve', 'paz', 'pureza', 'preto', 'azul'],
      cinza: ['chumbo', 'frio', 'nublado', 'branco', 'preto'],
      rosa: ['flor', 'menina', 'doce', 'vermelho', 'azul'],
      roxo: ['uva', 'berinjela', 'realeza', 'violeta', 'amarelo'],
      marrom: ['terra', 'madeira', 'chocolate', 'vermelho', 'azul'],
      laranja: ['fruta', 'sol', 'fogo', 'amarelo', 'vermelho'],
      violeta: ['flor', 'roxo', 'azul', 'vermelho', 'amarelo'],
      bege: ['areia', 'claro', 'neutro', 'branco', 'preto'],
      dourado: ['ouro', 'riqueza', 'sol', 'amarelo', 'vermelho'],
      prateado: ['prata', 'metal', 'frio', 'branco', 'preto'],
      turquesa: ['azul', 'verde', 'agua', 'mar', 'vermelho'],
      ciano: ['azul', 'verde', 'agua', 'mar', 'vermelho'],
      magenta: ['rosa', 'vermelho', 'azul', 'verde', 'amarelo'],
      salmao: ['peixe', 'rosa', 'laranja', 'vermelho', 'azul'],
      creme: ['branco', 'leite', 'claro', 'preto', 'vermelho'],
      chocolate: ['cacau', 'doce', 'marrom', 'vermelho', 'azul'],
      caramelo: ['doce', 'acucar', 'marrom', 'vermelho', 'azul'],
      grafite: ['chumbo', 'cinza', 'preto', 'branco', 'vermelho'],
    },
  },
  países: {
    words: [
      'brasil',
      'argentina',
      'canada',
      'mexico',
      'alemanha',
      'franca',
      'japao',
      'china',
      'russia',
      'india',
      'mocambique',
      'portugal',
      'espanha',
      'italia',
      'angola',
      'colombia',
      'peru',
      'chile',
      'uruguai',
      'paraguai',
    ],
    image: paises,
    hints: {
      brasil: ['america', 'portugues', 'verde', 'amarelo', 'rio'],
      argentina: ['america', 'espanhol', 'tango', 'buenos', 'aires'],
      canada: ['america', 'ingles', 'frio', 'maple', 'hoquei'],
      mexico: ['america', 'espanhol', 'calor', 'sombrero', 'mariachi'],
      alemanha: ['europa', 'alemao', 'cerveja', 'frio', 'berlim'],
      franca: ['europa', 'frances', 'torre', 'eiffel', 'paris'],
      japao: ['asia', 'japones', 'sushi', 'tecnologia', 'toquio'],
      china: ['asia', 'mandarim', 'muralha', 'pequim', 'panda'],
      russia: ['europa', 'russo', 'frio', 'moscou', 'urso'],
      india: ['asia', 'hindi', 'calor', 'bollywood', 'nova'],
      mocambique: ['africa', 'portugues', 'maputo', 'praia', 'mar'],
      portugal: ['europa', 'portugues', 'lisboa', 'fado', 'mar'],
      espanha: ['europa', 'espanhol', 'madri', 'paella', 'tourada'],
      italia: ['europa', 'italiano', 'roma', 'macarrao', 'pizza'],
      angola: ['africa', 'portugues', 'luanda', 'petroleo', 'praia'],
      colombia: ['america', 'espanhol', 'bogota', 'cafe', 'drogas'],
      peru: ['america', 'espanhol', 'lima', 'machu', 'picchu'],
      chile: ['america', 'espanhol', 'santiago', 'vinho', 'mar'],
      uruguai: ['america', 'espanhol', 'montevideo', 'carne', 'mar'],
      paraguai: ['america', 'espanhol', 'assuncao', 'guarani', 'rio'],
    },
  },
  profissões: {
    words: [
      'medico',
      'engenheiro',
      'professor',
      'advogado',
      'dentista',
      'enfermeiro',
      'arquiteto',
      'pintor',
      'ator',
      'cantor',
      'jornalista',
      'musico',
      'policial',
      'bombeiro',
      'motorista',
      'cozinheiro',
      'faxineiro',
      'padeiro',
      'jardineiro',
      'pedreiro',
      'programador',
      'designer',
      'veterinario',
      'fotografo',
      'piloto',
    ],
    image: profissoes,
    hints: {
      medico: ['saude', 'hospital', 'doente', 'receita', 'enfermeira'],
      engenheiro: ['construcao', 'obra', 'projeto', 'civil', 'arquiteto'],
      professor: ['escola', 'ensino', 'aluno', 'materia', 'diretor'],
      advogado: ['lei', 'justica', 'tribunal', 'cliente', 'juiz'],
      dentista: ['dente', 'escovar', 'caries', 'clinica', 'aparelho'],
      enfermeiro: ['saude', 'hospital', 'medico', 'paciente', 'sangue'],
      arquiteto: ['construcao', 'projeto', 'obra', 'engenheiro', 'civil'],
      pintor: ['tinta', 'quadro', 'arte', 'pincel', 'museu'],
      ator: ['teatro', 'filme', 'personagem', 'diretor', 'palco'],
      cantor: ['musica', 'voz', 'palco', 'disco', 'banda'],
      jornalista: ['noticia', 'reporter', 'jornal', 'tv', 'radio'],
      musico: ['instrumento', 'banda', 'palco', 'disco', 'cantor'],
      policial: ['lei', 'seguranca', 'crime', 'bandido', 'prisao'],
      bombeiro: ['fogo', 'incendio', 'resgate', 'agua', 'salvar'],
      motorista: ['carro', 'dirigir', 'transito', 'taxi', 'onibus'],
      cozinheiro: ['comida', 'restaurante', 'chef', 'prato', 'fogao'],
      faxineiro: ['limpeza', 'vassoura', 'rodo', 'chao', 'banheiro'],
      padeiro: ['pao', 'padaria', 'forno', 'farinha', 'massa'],
      jardineiro: ['planta', 'flor', 'jardim', 'terra', 'regador'],
      pedreiro: ['construcao', 'obra', 'cimento', 'tijolo', 'casa'],
      programador: ['computador', 'tecnologia', 'codigo', 'site', 'app'],
      designer: ['criativo', 'arte', 'projeto', 'grafico', 'web'],
      veterinario: ['animal', 'saude', 'cao', 'gato', 'consulta'],
      fotografo: ['foto', 'camera', 'imagem', 'lente', 'retrato'],
      piloto: ['aviao', 'voo', 'comandante', 'aeroporto', 'pista'],
    },
  },
  esportes: {
    words: [
      'futebol',
      'basquete',
      'volei',
      'natacao',
      'tenis',
      'golfe',
      'boxe',
      'corrida',
      'ciclismo',
      'surf',
      'skate',
      'ginastica',
      'judo',
      'karate',
      'atletismo',
      'handebol',
      'rugby',
      'beisebol',
      'hoquei',
      'patinacao',
      'esgrima',
    ],
    image: esportes,
    hints: {
      futebol: ['bola', 'gol', 'time', 'jogador', 'campo'],
      basquete: ['bola', 'cesta', 'ponto', 'time', 'quadra'],
      volei: ['bola', 'rede', 'ponto', 'time', 'quadra'],
      natacao: ['agua', 'piscina', 'nadador', 'medalha', 'olimpiada'],
      tenis: ['bola', 'raquete', 'ponto', 'quadra', 'saque'],
      golfe: ['bola', 'taco', 'buraco', 'green', 'swing'],
      boxe: ['luva', 'ringue', 'luta', 'nocaute', 'cinturao'],
      corrida: ['velocidade', 'pista', 'atleta', 'maratona', 'olimpiada'],
      ciclismo: ['bike', 'pedalar', 'pista', 'atleta', 'olimpiada'],
      surf: ['prancha', 'onda', 'mar', 'praia', 'campeonato'],
      skate: ['rodas', 'manobra', 'pista', 'half', 'pipe'],
      ginastica: ['salto', 'barra', 'trave', 'atleta', 'olimpiada'],
      judo: ['tatame', 'kimono', 'luta', 'medalha', 'olimpiada'],
      karate: ['tatame', 'kimono', 'luta', 'medalha', 'olimpiada'],
      atletismo: ['corrida', 'salto', 'arremesso', 'velocidade', 'olimpiada'],
      handebol: ['bola', 'gol', 'time', 'jogador', 'quadra'],
      rugby: ['bola', 'try', 'time', 'jogador', 'campo'],
      beisebol: ['bola', 'taco', 'time', 'jogador', 'campo'],
      hoquei: ['puck', 'gol', 'time', 'jogador', 'gelo'],
      patinacao: ['gelo', 'patins', 'pista', 'velocidade', 'artistico'],
      esgrima: ['espada', 'mascara', 'luta', 'medalha', 'olimpiada'],
    },
  },
}

export default categories
