import { StaticImageData } from 'next/image'
import animais from '@/assets/animais.png'
import frutas from '@/assets/frutas.png'
import objetos from '@/assets/objetos.png'
import cores from '@/assets/cores.png'
import paises from '@/assets/paises.png'
import profissoes from '@/assets/profissoes.png'
import esportes from '@/assets/esportes.png'

const categories: {
  [key: string]: {
    words: string[]
    image: StaticImageData
  }
} = {
  animais: {
    words: [
      'cachorro',
      'gato',
      'elefante',
      'tigre',
      'leão',
      'girafa',
      'urso',
      'coelho',
      'raposa',
      'veado',
      'pato',
      'galinha',
      'vaca',
      'cavalo',
      'borboleta',
      'abelha',
      'formiga',
      'aranha',
      'escorpião',
      'lagarto',
      'cobra',
      'jacaré',
      'tartaruga',
      'peixe',
    ],
    image: animais,
  },
  frutas: {
    words: [
      'maca',
      'banana',
      'laranja',
      'uva',
      'melancia',
      'abacaxi',
      'morango',
      'manga',
      'kiwi',
      'pera',
      'pessego',
      'ameixa',
      'limao',
      'abacate',
      'caqui',
      'pitaya',
      'pitanga',
    ],
    image: frutas,
  },
  objetos: {
    words: [
      'mesa',
      'cadeira',
      'computador',
      'telefone',
      'livro',
      'caderno',
      'caneta',
      'lapis',
      'janela',
      'porta',
      'cama',
      'travesseiro',
      'cobertor',
      'abajur',
      'sofa',
      'televisao',
      'geladeira',
      'fogao',
      'microondas',
      'liquidificador',
    ],
    image: objetos,
  },
  cores: {
    words: [
      'vermelho',
      'azul',
      'amarelo',
      'verde',
      'preto',
      'branco',
      'cinza',
      'rosa',
      'roxo',
      'marrom',
      'laranja',
      'violeta',
      'bege',
      'dourado',
      'prateado',
      'turquesa',
      'ciano',
      'magenta',
      'salmao',
      'creme',
      'chocolate',
      'caramelo',
      'grafite',
    ],
    image: cores,
  },
  países: {
    words: [
      'brasil',
      'argentina',
      'canada',
      'mexico',
      'alemanha',
      'franca',
      'japao',
      'china',
      'russia',
      'india',
      'mocambique',
      'portugal',
      'espanha',
      'italia',
      'angola',
      'colombia',
      'peru',
      'chile',
      'uruguai',
      'paraguai',
    ],
    image: paises,
  },
  profissões: {
    words: [
      'medico',
      'engenheiro',
      'professor',
      'advogado',
      'dentista',
      'enfermeiro',
      'arquiteto',
      'pintor',
      'ator',
      'cantor',
      'jornalista',
      'musico',
      'policial',
      'bombeiro',
      'motorista',
      'cozinheiro',
      'faxineiro',
      'padeiro',
      'jardineiro',
      'pedreiro',
      'programador',
      'designer',
      'veterinario',
      'fotografo',
      'piloto',
    ],
    image: profissoes,
  },
  esportes: {
    words: [
      'futebol',
      'basquete',
      'vôlei',
      'natação',
      'tênis',
      'golfe',
      'boxe',
      'corrida',
      'ciclismo',
      'surf',
      'skate',
      'ginástica',
      'judô',
      'karatê',
      'atletismo',
      'handebol',
      'rugby',
      'beisebol',
      'hóquei',
      'patinação',
      'esgrima',
    ],
    image: esportes,
  },
}

export default categories
