const categories = {
  Animais: {
    words: [
      'cachorro',
      'gato',
      'elefante',
      'tigre',
      'leao',
      'girafa',
      'urso',
      'coelho',
      'raposa',
      'veado',
      'pato',
      'galinha',
      'vaca',
      'cavalo',
      'borboleta',
      'abelha',
      'formiga',
      'aranha',
      'escorpiao',
      'lagarto',
      'cobra',
      'jacare',
      'tartaruga',
      'peixe',
      'papagaio',
      'passaro',
      'coruja',
      'pombo',
      'pavao',
    ],
    hints: {
      cachorro: [
        'o melhor amigo do homem',
        'late',
        'cão de guarda',
        'animal de estimação',
        'ama ossos',
      ],
      gato: [
        'ronrona',
        'animal de estimação',
        'gosta de peixe',
        'independente',
        'tem bigodes',
      ],
      elefante: [
        'tem tromba',
        'grande mamífero',
        'vive em savanas',
        'tem grandes orelhas',
        'come muito',
      ],
      tigre: [
        'tem listras',
        'grande felino',
        'selvagem',
        'vive na Ásia',
        'é feroz',
      ],
      leao: [
        'o rei da selva',
        'tem juba',
        'vive em savanas',
        'grande felino',
        'caça em grupo',
      ],
      girafa: [
        'pescoço longo',
        'vive em savanas',
        'alta',
        'manchas',
        'come folhas de árvores',
      ],
      urso: [
        'hiberna no inverno',
        'grande mamífero',
        'vive em florestas',
        'ama mel',
        'pode ser polar',
      ],
      coelho: [
        'gosta de cenouras',
        'tem orelhas longas',
        'é rápido',
        'animal de estimação',
        'tem pelo macio',
      ],
      raposa: [
        'astuta',
        'tem rabo espesso',
        'vive em florestas',
        'parece um cão',
        'pelagem laranja',
      ],
      veado: [
        'tem chifres',
        'vive em florestas',
        'animal herbívoro',
        'é rápido',
        'pode ser caçado',
      ],
      pato: [
        'nada em lagos',
        'ave aquática',
        'faz quack',
        'tem penas',
        'pode voar',
      ],
      galinha: [
        'produz ovos',
        'vive em galinheiros',
        'ave doméstica',
        'faz cocoricó',
        'pode ser caipira',
      ],
      vaca: [
        'produz leite',
        'vive em fazendas',
        'grande herbívoro',
        'mugir',
        'tem manchas',
      ],
      cavalo: [
        'usado para montaria',
        'corre rápido',
        'vive em estábulos',
        'grande mamífero',
        'pode ser selvagem',
      ],
      borboleta: [
        'tem asas coloridas',
        'come néctar',
        'passa por metamorfose',
        'inseto',
        'voa',
      ],
      abelha: [
        'produz mel',
        'vive em colmeias',
        'inseto',
        'pode picar',
        'faz zumbido',
      ],
      formiga: [
        'trabalhadora',
        'vive em formigueiros',
        'pequeno inseto',
        'carrega peso',
        'trabalha em equipe',
      ],
      aranha: [
        'tece teias',
        'pode ser venenosa',
        'oito patas',
        'inseto',
        'pode ser assustadora',
      ],
      escorpiao: [
        'tem veneno',
        'usa pinças',
        'vive em desertos',
        'tem cauda',
        'inseto noturno',
      ],
      lagarto: [
        'tem cauda comprida',
        'escamas',
        'reptil',
        'pode perder a cauda',
        'vive em ambientes quentes',
      ],
      cobra: [
        'não tem patas',
        'rasteja',
        'reptil',
        'pode ser venenosa',
        'sibila',
      ],
      jacare: [
        'vive em rios',
        'reptil',
        'grande predador',
        'tem dentes afiados',
        'verde',
      ],
      tartaruga: [
        'vive em água e terra',
        'tem casco',
        'reptil',
        'é lenta',
        'pode ser marinha',
      ],
      peixe: [
        'vive na água',
        'tem escamas',
        'usa nadadeiras',
        'respira por brânquias',
        'pode ser de aquário',
      ],
      papagaio: [
        'pode falar',
        'tem penas coloridas',
        'vive em florestas tropicais',
        'bico curvado',
        'ave',
      ],
      passaro: [
        'tem bico e penas',
        'pode voar',
        'canta',
        'vive em árvores',
        'pode ser de várias cores',
      ],
      coruja: [
        'caça à noite',
        'tem visão noturna',
        'vive em florestas',
        'associada à sabedoria',
        'ave de rapina',
      ],
      pombo: [
        'vive em cidades',
        'pode voar',
        'faz ninho em prédios',
        'ave',
        'pode ser mensageiro',
      ],
      pavao: [
        'tem cauda colorida',
        'ave',
        'faz exibição para atrair parceira',
        'vive em florestas',
        'azul e verde',
      ],
      avestruz: [
        'não pode voar',
        'corre rápido',
        'vive em savanas',
        'ave grande',
        'tem pescoço longo',
      ],
    },
  },
  Frutas: {
    words: [
      'maca',
      'banana',
      'laranja',
      'uva',
      'melancia',
      'abacaxi',
      'morango',
      'manga',
      'kiwi',
      'pera',
      'pessego',
      'ameixa',
      'limao',
      'abacate',
      'caqui',
      'pitaya',
      'pitanga',
      'cereja',
      'figo',
      'goiaba',
      'maracuja',
      'melao',
      'mamao',
      'nectarina',
    ],
    hints: {
      maca: [
        'fruta que mantém o médico longe',
        'pode ser vermelha, verde ou amarela',
        'símbolo da tentação',
        'usada em tortas',
        'é crocante',
      ],
      banana: [
        'aquilo que macacos gostam de comer',
        'amarela quando madura',
        'rica em potássio',
        'pode ser nanica ou prata',
        'usada em vitaminas',
      ],
      laranja: [
        'fruta cítrica usada em sucos',
        'tem casca alaranjada',
        'rica em vitamina C',
        'pode ser doce ou azeda',
        'usada em marmelada',
      ],
      uva: [
        'usada na produção de vinho',
        'pode ser verde, vermelha ou roxa',
        'vem em cachos',
        'pode ser consumida fresca ou seca',
        'é pequena e doce',
      ],
      melancia: [
        'grande fruta verde por fora e vermelha por dentro',
        'tem muitas sementes',
        'é suculenta e refrescante',
        'muito consumida no verão',
        'pode ser fatiada',
      ],
      abacaxi: [
        'tem uma coroa de folhas',
        'casca espinhosa e amarela',
        'polpa amarela e suculenta',
        'pode ser ácido ou doce',
        'usado em sucos e sobremesas',
      ],
      morango: [
        'fruta pequena e vermelha',
        'tem sementes na superfície',
        'usado em sobremesas e doces',
        'rico em vitamina C',
        'muito apreciado com chocolate',
      ],
      manga: [
        'fruta tropical de polpa amarela',
        'tem uma grande semente no meio',
        'usada em sucos e saladas',
        'pode ser consumida verde ou madura',
        'rica em fibras',
      ],
      kiwi: [
        'tem casca marrom e peluda',
        'polpa verde brilhante',
        'semente preta no interior',
        'sabor doce e ácido',
        'rica em vitamina C',
      ],
      pera: [
        'fruta de formato semelhante a uma lágrima',
        'polpa branca e suculenta',
        'pode ser verde ou amarela',
        'rica em fibras',
        'usada em saladas de frutas',
      ],
      pessego: [
        'tem casca aveludada',
        'polpa suculenta e amarela',
        'sabor doce',
        'pode ser consumido fresco ou em caldas',
        'tem um caroço no meio',
      ],
      ameixa: [
        'fruta de casca lisa',
        'polpa doce e suculenta',
        'pode ser roxa ou vermelha',
        'usada em doces e compotas',
        'tem um caroço pequeno',
      ],
      limao: [
        'fruta cítrica e ácida',
        'casca verde ou amarela',
        'usado em sucos e temperos',
        'rico em vitamina C',
        'pode ser siciliano ou taiti',
      ],
      abacate: [
        'fruta de casca verde e rugosa',
        'polpa cremosa',
        'usado em saladas e guacamoles',
        'rico em gorduras boas',
        'tem um grande caroço no meio',
      ],
      caqui: [
        'fruta de polpa macia e doce',
        'casca fina e laranja',
        'consumido fresco ou em sobremesas',
        'rico em vitaminas',
        'tem um pequeno caroço',
      ],
      pitaya: [
        'fruta exótica de casca rosa',
        'polpa branca ou vermelha com sementes pretas',
        'sabor doce e suave',
        'também conhecida como fruta-dragão',
        'usada em saladas e sucos',
      ],
      pitanga: [
        'fruta pequena e vermelha',
        'sabor doce e ácido',
        'usada em sucos e compotas',
        'tem um pequeno caroço',
        'muito cultivada no Brasil',
      ],
      cereja: [
        'fruta pequena e vermelha',
        'sabor doce',
        'usada em sobremesas e drinks',
        'tem um pequeno caroço',
        'muito apreciada no natal',
      ],
      figo: [
        'fruta de casca verde ou roxa',
        'polpa doce e rosada',
        'usado em doces e compotas',
        'rico em fibras',
        'tem pequenas sementes',
      ],
      goiaba: [
        'fruta de casca verde ou amarela',
        'polpa rosa ou branca',
        'usada em sucos e doces',
        'tem muitas sementes',
        'rica em vitamina C',
      ],
      maracuja: [
        'fruta de casca amarela ou roxa',
        'polpa azeda e cheia de sementes',
        'usada em sucos e sobremesas',
        'tem efeito calmante',
        'muito consumida no verão',
      ],
      melao: [
        'fruta de casca amarela ou verde',
        'polpa suculenta e doce',
        'usado em saladas de frutas',
        'rico em água',
        'muito refrescante',
      ],
      mamao: [
        'fruta de casca laranja',
        'polpa doce e alaranjada',
        'usada em saladas de frutas',
        'rica em vitaminas',
        'tem muitas sementes',
      ],
      nectarina: [
        'fruta de casca lisa',
        'polpa doce e suculenta',
        'parecida com o pêssego',
        'usada em saladas de frutas',
        'rica em vitaminas',
      ],
    },
  },
  Objetos: {
    words: [
      'mesa',
      'cadeira',
      'computador',
      'telefone',
      'livro',
      'caderno',
      'caneta',
      'lapis',
      'janela',
      'porta',
      'cama',
      'travesseiro',
      'cobertor',
      'abajur',
      'sofa',
      'televisao',
      'geladeira',
      'fogao',
      'microondas',
      'liquidificador',
    ],
    hints: {
      mesa: [
        'móvel onde se come ou trabalha',
        'tem quatro pés',
        'usada em escritórios',
        'feita de madeira',
        'usada em salas de jantar',
      ],
      cadeira: [
        'móvel para sentar',
        'tem encosto',
        'usada em salas e escritórios',
        'tem quatro pés',
        'pode ser estofada',
      ],
      computador: [
        'máquina para trabalhar ou jogar',
        'tem teclado e mouse',
        'conectado à internet',
        'usado em escritórios',
        'tem monitor',
      ],
      telefone: [
        'usado para fazer ligações',
        'pode ser fixo ou celular',
        'tem números para discar',
        'usado para comunicação',
        'pode enviar mensagens',
      ],
      livro: [
        'coleção de páginas para leitura',
        'tem capa',
        'pode ser de ficção ou não-ficção',
        'usado em estudos',
        'tem autor e título',
      ],
      caderno: [
        'usado para escrever notas',
        'tem muitas folhas',
        'usado em escolas',
        'pode ser espiral',
        'tem capa',
      ],
      caneta: [
        'usada para escrever',
        'tem tinta',
        'pode ser azul ou preta',
        'tem ponta',
        'usada em escritórios',
      ],
      lapis: [
        'usado para escrever ou desenhar',
        'tem grafite',
        'pode ser apontado',
        'tem borracha na ponta',
        'usado em escolas',
      ],
      janela: [
        'abertura na parede',
        'feita de vidro',
        'deixa entrar luz',
        'pode ser aberta',
        'usada para ventilação',
      ],
      porta: [
        'usada para entrar e sair de um cômodo',
        'pode ser de madeira ou metal',
        'tem maçaneta',
        'pode ser trancada',
        'separa ambientes',
      ],
      cama: [
        'usada para dormir',
        'tem colchão',
        'usada em quartos',
        'pode ter lençóis',
        'tem travesseiros',
      ],
      travesseiro: [
        'usado para apoiar a cabeça ao dormir',
        'macio',
        'usado em camas',
        'pode ter fronha',
        'enche de penas ou espuma',
      ],
      cobertor: [
        'usado para se cobrir ao dormir',
        'mantém quente',
        'usado em camas',
        'feito de lã ou algodão',
        'usado no inverno',
      ],
      abajur: [
        'usado para iluminar',
        'tem lâmpada',
        'usado em mesas de cabeceira',
        'tem cúpula',
        'usado para leitura',
      ],
      sofa: [
        'móvel para sentar',
        'usado em salas de estar',
        'pode ser de dois ou três lugares',
        'pode ser estofado',
        'usado para descansar',
      ],
      televisao: [
        'usada para ver programas',
        'tem tela',
        'usada em salas de estar',
        'tem controle remoto',
        'pode ser de plasma ou LCD',
      ],
      geladeira: [
        'usada para conservar alimentos',
        'mantém frio',
        'usada em cozinhas',
        'tem portas',
        'pode ter congelador',
      ],
      fogao: [
        'usado para cozinhar',
        'tem bocas e forno',
        'usado em cozinhas',
        'pode ser a gás ou elétrico',
        'usado com panelas',
      ],
      microondas: [
        'usado para aquecer alimentos',
        'tem timer',
        'usado em cozinhas',
        'funciona com eletricidade',
        'rápido e prático',
      ],
      liquidificador: [
        'usado para fazer vitaminas e sucos',
        'tem lâminas afiadas',
        'usado em cozinhas',
        'funciona com eletricidade',
        'tem copo de vidro ou plástico',
      ],
    },
  },
  Cores: {
    words: [
      'vermelho',
      'azul',
      'amarelo',
      'verde',
      'preto',
      'branco',
      'cinza',
      'rosa',
      'roxo',
      'marrom',
      'laranja',
      'violeta',
      'bege',
      'dourado',
      'prateado',
      'turquesa',
      'ciano',
      'magenta',
      'salmao',
      'creme',
      'chocolate',
      'caramelo',
      'grafite',
    ],
    hints: {
      vermelho: [
        'cor do sangue',
        'cor do coração',
        'associado ao amor',
        'usado em semáforos',
        'uma rosa dessa cor',
      ],
      azul: [
        'cor do céu',
        'cor do mar',
        'associado à calma',
        'usado em bandeiras',
        'pode ser claro ou escuro',
      ],
      amarelo: [
        'cor do sol',
        'associado à alegria',
        'usado em semáforos',
        'cor da banana',
        'mistura de vermelho e verde',
      ],
      verde: [
        'cor das folhas',
        'associado à natureza',
        'cor do limão',
        'usado em semáforos',
        'mistura de azul e amarelo',
      ],
      preto: [
        'cor da noite',
        'associado ao luto',
        'usado em roupas',
        'oposto ao branco',
        'cor do carvão',
      ],
      branco: [
        'cor da neve',
        'associado à paz',
        'usado em bandeiras',
        'oposto ao preto',
        'cor das nuvens',
      ],
      cinza: [
        'mistura de preto e branco',
        'cor do chumbo',
        'associado à neutralidade',
        'usado em roupas',
        'cor do céu nublado',
      ],
      rosa: [
        'cor das flores',
        'associado à feminilidade',
        'mistura de vermelho e branco',
        'usado em roupas',
        'cor do algodão-doce',
      ],
      roxo: [
        'cor da uva',
        'associado à realeza',
        'mistura de azul e vermelho',
        'usado em roupas',
        'cor da lavanda',
      ],
      marrom: [
        'cor da terra',
        'associado à madeira',
        'usado em móveis',
        'cor do chocolate',
        'mistura de vermelho e verde',
      ],
      laranja: [
        'cor da fruta de mesmo nome',
        'mistura de vermelho e amarelo',
        'associado à energia',
        'usado em roupas',
        'cor do pôr do sol',
      ],
      violeta: [
        'cor da flor de mesmo nome',
        'mistura de azul e roxo',
        'associado à espiritualidade',
        'usado em roupas',
        'cor das ametistas',
      ],
      bege: [
        'cor da areia',
        'associado à neutralidade',
        'usado em roupas',
        'mistura de branco e marrom',
        'cor dos deserto',
      ],
      dourado: [
        'cor do ouro',
        'associado à riqueza',
        'usado em joias',
        'cor do sol',
        'mistura de amarelo e marrom',
      ],
      prateado: [
        'cor da prata',
        'associado ao futurismo',
        'usado em joias',
        'cor dos metais',
        'mistura de branco e cinza',
      ],
      turquesa: [
        'cor do mar',
        'mistura de azul e verde',
        'associado à serenidade',
        'usado em joias',
        'cor das águas cristalinas',
      ],
      ciano: [
        'mistura de azul e verde',
        'associado à água',
        'usado em impressoras',
        'cor do céu',
        'cor das águas tropicais',
      ],
      magenta: [
        'mistura de vermelho e roxo',
        'associado à criatividade',
        'usado em impressoras',
        'cor das flores',
        'cor das frutas tropicais',
      ],
      salmao: [
        'cor do peixe de mesmo nome',
        'mistura de rosa e laranja',
        'associado à suavidade',
        'usado em roupas',
        'cor dos frutos do mar',
      ],
      creme: [
        'cor do leite',
        'mistura de branco e amarelo',
        'associado à suavidade',
        'usado em roupas',
        'cor dos laticínios',
      ],
      chocolate: [
        'cor do doce de mesmo nome',
        'mistura de marrom e preto',
        'associado ao prazer',
        'usado em roupas',
        'cor dos alimentos',
      ],
      caramelo: [
        'cor do doce de mesmo nome',
        'mistura de amarelo e marrom',
        'associado à doçura',
        'usado em roupas',
        'cor dos alimentos',
      ],
      grafite: [
        'mistura de preto e cinza',
        'associado à modernidade',
        'usado em lápis',
        'cor dos metais',
        'cor das ruas',
      ],
    },
  },
  Paises: {
    words: [
      'brasil',
      'argentina',
      'canada',
      'mexico',
      'alemanha',
      'franca',
      'japao',
      'china',
      'russia',
      'india',
      'mocambique',
      'portugal',
      'espanha',
      'italia',
      'angola',
      'colombia',
      'peru',
      'chile',
      'uruguai',
      'paraguai',
    ],
    hints: {
      brasil: [
        'país da América do Sul',
        'fala português',
        'conhecido pelo carnaval',
        'tem a maior floresta tropical',
        'é o maior produtor de café',
      ],
      argentina: [
        'país da América do Sul',
        'fala espanhol',
        'famoso pelo tango',
        'tem o melhor churrasco',
        'capital é Buenos Aires',
      ],
      canada: [
        'país da América do Norte',
        'fala inglês e francês',
        'famoso pelo xarope de bordo',
        'tem os lagos mais bonitos',
        'capital é Ottawa',
      ],
      mexico: [
        'país da América do Norte',
        'fala espanhol',
        'famoso pelas pirâmides',
        'tem a festa do Dia dos Mortos',
        'capital é Cidade do México',
      ],
      alemanha: [
        'país da Europa',
        'fala alemão',
        'famoso pela cerveja',
        'capital é Berlim',
        'tem o muro mais famoso',
      ],
      franca: [
        'país da Europa',
        'fala francês',
        'conhecido pela Torre Eiffel',
        'capital é Paris',
        'famoso pelo vinho',
      ],
      japao: [
        'país da Ásia',
        'fala japonês',
        'famoso pelo sushi',
        'tem os melhores eletrônicos',
        'capital é Tóquio',
      ],
      china: [
        'país da Ásia',
        'fala mandarim',
        'conhecido pela Grande Muralha',
        'capital é Pequim',
        'tem a maior população do mundo',
      ],
      russia: [
        'país da Europa e Ásia',
        'fala russo',
        'conhecido pelo frio',
        'capital é Moscou',
        'famoso pela vodka',
      ],
      india: [
        'país da Ásia',
        'fala hindi',
        'conhecido pelo Taj Mahal',
        'capital é Nova Déli',
        'famoso por Bollywood',
      ],
      mocambique: [
        'país da África',
        'fala português',
        'conhecido pelas praias',
        'capital é Maputo',
        'famoso pela ilha de Moçambique',
      ],
      portugal: [
        'país da Europa',
        'fala português',
        'conhecido pelo fado',
        'capital é Lisboa',
        'famoso pelo vinho do Porto',
      ],
      espanha: [
        'país da Europa',
        'fala espanhol',
        'conhecido pela paella',
        'capital é Madri',
        'famoso pelas touradas',
      ],
      italia: [
        'país da Europa',
        'fala italiano',
        'conhecido pelo macarrão',
        'capital é Roma',
        'famoso pela pizza',
      ],
      angola: [
        'país da África',
        'fala português',
        'conhecido pelo petróleo',
        'capital é Luanda',
        'famoso pela música kuduro',
      ],
      colombia: [
        'país da América do Sul',
        'fala espanhol',
        'conhecido pelo café',
        'capital é Bogotá',
        'famoso por Cartagena',
      ],
      peru: [
        'país da América do Sul',
        'fala espanhol',
        'conhecido por Machu Picchu',
        'capital é Lima',
        'famoso pelo ceviche',
      ],
      chile: [
        'país da América do Sul',
        'fala espanhol',
        'conhecido pelo vinho',
        'capital é Santiago',
        'famoso pelo deserto do Atacama',
      ],
      uruguai: [
        'país da América do Sul',
        'fala espanhol',
        'conhecido pela carne',
        'capital é Montevidéu',
        'famoso por Punta del Este',
      ],
      paraguai: [
        'país da América do Sul',
        'fala espanhol',
        'conhecido pela música',
        'capital é Assunção',
        'famoso pelo tereré',
      ],
    },
  },
  Profissoes: {
    words: [
      'medico',
      'engenheiro',
      'professor',
      'advogado',
      'dentista',
      'enfermeiro',
      'arquiteto',
      'pintor',
      'ator',
      'cantor',
      'jornalista',
      'musico',
      'policial',
      'bombeiro',
      'motorista',
      'cozinheiro',
      'faxineiro',
      'padeiro',
      'jardineiro',
      'pedreiro',
      'programador',
      'designer',
      'veterinario',
      'fotografo',
      'piloto',
    ],
    hints: {
      medico: [
        'cuida da saúde das pessoas',
        'trabalha em hospitais',
        'prescreve medicamentos',
        'realiza cirurgias',
        'usa jaleco',
      ],
      engenheiro: [
        'planeja e constrói obras',
        'trabalha em obras',
        'desenha projetos',
        'tem conhecimento em matemática',
        'usa capacete',
      ],
      professor: [
        'ensina alunos',
        'trabalha em escolas',
        'dá aulas',
        'corrige provas',
        'prepara aulas',
      ],
      advogado: [
        'defende clientes na justiça',
        'trabalha em escritórios',
        'estuda leis',
        'vai a tribunais',
        'usa terno',
      ],
      dentista: [
        'cuida dos dentes das pessoas',
        'trabalha em consultórios',
        'faz obturações',
        'realiza limpezas',
        'usa máscara',
      ],
      enfermeiro: [
        'ajuda médicos',
        'trabalha em hospitais',
        'cuida de pacientes',
        'administra medicamentos',
        'usa uniforme',
      ],
      arquiteto: [
        'desenha projetos de construção',
        'trabalha em escritórios',
        'faz maquetes',
        'planeja casas',
        'usa régua',
      ],
      pintor: [
        'pinta paredes e quadros',
        'trabalha em obras',
        'usa pincel',
        'mistura tintas',
        'usa avental',
      ],
      ator: [
        'interpreta personagens',
        'trabalha em teatros e filmes',
        'ensaia textos',
        'faz cenas',
        'usa figurinos',
      ],
      cantor: [
        'canta músicas',
        'trabalha em shows',
        'grava CDs',
        'faz turnês',
        'usa microfone',
      ],
      jornalista: [
        'informa as notícias',
        'trabalha em jornais e TVs',
        'escreve reportagens',
        'entrevista pessoas',
        'usa bloco de notas',
      ],
      musico: [
        'toca instrumentos',
        'trabalha em bandas e orquestras',
        'compõe músicas',
        'faz shows',
        'usa partitura',
      ],
      policial: [
        'mantém a ordem pública',
        'trabalha nas ruas',
        'prende criminosos',
        'faz patrulhas',
        'usa farda',
      ],
      bombeiro: [
        'apaga incêndios',
        'trabalha em quartéis',
        'resgata pessoas',
        'usa mangueiras',
        'usa capacete',
      ],
      motorista: [
        'dirige veículos',
        'trabalha nas ruas',
        'transporta pessoas ou cargas',
        'tem carteira de habilitação',
        'usa volante',
      ],
      cozinheiro: [
        'prepara alimentos',
        'trabalha em restaurantes',
        'cria receitas',
        'usa fogão',
        'usa avental',
      ],
      faxineiro: [
        'faz limpeza',
        'trabalha em prédios e casas',
        'usa vassoura',
        'lava janelas',
        'usa produtos de limpeza',
      ],
      padeiro: [
        'faz pães e bolos',
        'trabalha em padarias',
        'usa forno',
        'mistura farinha',
        'usa avental',
      ],
      jardineiro: [
        'cuida de jardins',
        'trabalha em áreas verdes',
        'planta flores',
        'corta grama',
        'usa ferramentas de jardinagem',
      ],
      pedreiro: [
        'constrói casas e edifícios',
        'trabalha em obras',
        'assenta tijolos',
        'usa cimento',
        'usa capacete',
      ],
      programador: [
        'escreve códigos de computador',
        'trabalha em empresas de tecnologia',
        'cria softwares',
        'usa computador',
        'conhece linguagens de programação',
      ],
      designer: [
        'cria projetos gráficos',
        'trabalha em agências de publicidade',
        'usa programas de edição',
        'desenha logotipos',
        'cria layouts',
      ],
      veterinario: [
        'cuida da saúde dos animais',
        'trabalha em clínicas veterinárias',
        'prescreve medicamentos',
        'faz cirurgias',
        'usa jaleco',
      ],
      fotografo: [
        'tira fotos',
        'trabalha em estúdios e eventos',
        'usa câmera',
        'edita imagens',
        'faz ensaios fotográficos',
      ],
      piloto: [
        'comanda aviões',
        'trabalha em companhias aéreas',
        'faz voos',
        'usa fone de ouvido',
        'conhece rotas',
      ],
    },
  },
  Esportes: {
    words: [
      'futebol',
      'basquete',
      'volei',
      'natacao',
      'tenis',
      'golfe',
      'boxe',
      'corrida',
      'ciclismo',
      'surf',
      'skate',
      'ginastica',
      'judo',
      'karate',
      'atletismo',
      'handebol',
      'rugby',
      'beisebol',
      'hoquei',
      'patinacao',
      'esgrima',
    ],
    hints: {
      futebol: [
        'esporte com bola',
        'jogado com os pés',
        'tem 11 jogadores por time',
        'tem goleiro',
        'o objetivo é fazer gols',
      ],
      basquete: [
        'esporte com bola',
        'jogado com as mãos',
        'tem 5 jogadores por time',
        'o objetivo é fazer cestas',
        'usado em quadras',
      ],
      volei: [
        'esporte com bola',
        'jogado com as mãos',
        'tem 6 jogadores por time',
        'o objetivo é fazer pontos',
        'tem rede',
      ],
      natacao: [
        'esporte na água',
        'usado em piscinas',
        'tem várias modalidades',
        'usado em competições olímpicas',
        'tem nadadores',
      ],
      tenis: [
        'esporte com bola',
        'jogado com raquetes',
        'pode ser individual ou em duplas',
        'usado em quadras',
        'o objetivo é fazer pontos',
      ],
      golfe: [
        'esporte com bola',
        'usado em campos',
        'jogado com tacos',
        'o objetivo é acertar buracos',
        'usado em competições',
      ],
      boxe: [
        'esporte de luta',
        'usado em ringues',
        'tem luvas',
        'o objetivo é nocautear',
        'tem cinturões de campeão',
      ],
      corrida: [
        'esporte de velocidade',
        'usado em pistas',
        'tem várias distâncias',
        'usado em competições olímpicas',
        'tem maratonas',
      ],
      ciclismo: [
        'esporte com bicicletas',
        'usado em pistas e estradas',
        'tem várias modalidades',
        'usado em competições olímpicas',
        'tem ciclistas',
      ],
      surf: [
        'esporte na água',
        'usado em praias',
        'jogado com pranchas',
        'o objetivo é pegar ondas',
        'usado em campeonatos',
      ],
      skate: [
        'esporte com pranchas',
        'usado em pistas',
        'tem várias modalidades',
        'usado em competições',
        'tem skatistas',
      ],
      ginastica: [
        'esporte de solo',
        'usado em competições olímpicas',
        'tem várias modalidades',
        'usado em academias',
        'tem ginastas',
      ],
      judo: [
        'esporte de luta',
        'usado em tatames',
        'tem quimonos',
        'usado em competições olímpicas',
        'tem faixas de graduação',
      ],
      karate: [
        'esporte de luta',
        'usado em tatames',
        'tem quimonos',
        'usado em competições olímpicas',
        'tem faixas de graduação',
      ],
      atletismo: [
        'esporte de pista',
        'usado em competições olímpicas',
        'tem várias modalidades',
        'usado em estádios',
        'tem atletas',
      ],
      handebol: [
        'esporte com bola',
        'jogado com as mãos',
        'tem 7 jogadores por time',
        'o objetivo é fazer gols',
        'usado em quadras',
      ],
      rugby: [
        'esporte com bola',
        'jogado com as mãos e pés',
        'tem 15 jogadores por time',
        'o objetivo é fazer tries',
        'usado em campos',
      ],
      beisebol: [
        'esporte com bola',
        'jogado com tacos',
        'tem 9 jogadores por time',
        'o objetivo é fazer pontos',
        'usado em campos',
      ],
      hoquei: [
        'esporte com disco',
        'usado em pistas de gelo',
        'jogado com tacos',
        'tem 6 jogadores por time',
        'o objetivo é fazer gols',
      ],
      patinacao: [
        'esporte de gelo',
        'usado em pistas de gelo',
        'tem várias modalidades',
        'usado em competições olímpicas',
        'tem patinadores',
      ],
      esgrima: [
        'esporte de luta',
        'usado em competições olímpicas',
        'jogado com espadas',
        'usado em pistas',
        'tem esgrimistas',
      ],
    },
  },
}

module.exports = categories
